export interface IUser {
    id: number,
    last_login: string,
    is_superuser: boolean,
    username: string,
    is_staff: boolean,
    is_active: boolean,
    date_joined: string,
    first_name: string,
    last_name: string,
    email: string,
    bio: string,
    phone_number: string,
    snapchat: string,
    instagram: string,
    discord: string,
    groupme: string,
    verified: boolean,
    rating: number,
    profile_picture: string,
}